# Application
spring.application.name=eventify-backend
server.port=8080

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/eventify_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
logging.level.liquibase=DEBUG
logging.level.org.springframework.boot.liquibase=DEBUG

# JWT settings
jwt.secret=YourSuperSecretKeyForJwtSigningChangeMeInProduction1234567890
jwt.expiration-ms=3600000